"""add_tags_and_todo_tags

Revision ID: 10f666ec2764
Revises: b00000000000
Create Date: 2026-10-03 05:20:08.173217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f666ec2764'
down_revision: Union[str, None] = 'b00000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_created', table_name='todos')
    op.drop_index('ix_todos_user_completed_created', table_name='todos')
    op.create_index('ix_todos_user_completed_created', 'todos', ['user_id', 'completed', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_completed_created', table_name='todos')
    op.create_index('ix_todos_user_completed_created', 'todos', ['user_id', 'completed', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_todos_user_created', 'todos', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
