"""create_tags_tables

Revision ID: 192178a87c5c
Revises: 10f666ec2764
Create Date: 2026-10-03 16:19:38.666353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192178a87c5c'
down_revision: Union[str, None] = '10f666ec2764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_index('uq_tag_user_id_name_lower', 'tags', ['user_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('todo_tags',
    sa.Column('todo_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('todo_id', 'tag_id')
    )
    op.create_index('ix_todo_tags_tag_id', 'todo_tags', ['tag_id'], unique=False)
    op.create_index('ix_todo_tags_todo_id', 'todo_tags', ['todo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_tags_todo_id', table_name='todo_tags')
    op.drop_index('ix_todo_tags_tag_id', table_name='todo_tags')
    op.drop_table('todo_tags')
    op.drop_index('uq_tag_user_id_name_lower', table_name='tags')
    op.drop_index('ix_tags_user_id', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
