"""add_todo_indexes

Revision ID: b00000000000
Revises: a0790c76a129
Create Date: 2026-10-03 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00000000000'
down_revision: Union[str, None] = 'a0790c76a129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_todos_user_completed_created', 'todos', ['user_id', 'completed', sa.text('created_at DESC')])
    op.create_index('ix_todos_user_created', 'todos', ['user_id', sa.text('created_at DESC')])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_created', table_name='todos')
    op.drop_index('ix_todos_user_completed_created', table_name='todos')
    # ### end Alembic commands ###
